version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: dbexhibition
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
